package com.maahish.enums;

public enum NotificationType {
    SELLER_REGISTRATION_PENDING,
    SELLER_APPROVED,
    SELLER_REJECTED,
    SELLER_SUSPENDED,
    SELLER_ACTIVATED,
    NEW_ORDER,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PRODUCT_OUT_OF_STOCK,
    NEW_USER_REGISTERED
}
